export const STANDARD_PEDIATRIC_SERVICES = [
    // CONSULTATION
    { code: "CON-001", name: "OPD Consultation - Standard", category: "CONSULTATION", basePrice: 500, taxPercent: 0 },
    { code: "CON-002", name: "OPD Consultation - Specialist", category: "CONSULTATION", basePrice: 800, taxPercent: 0 },
    { code: "CON-003", name: "Emergency Consultation", category: "CONSULTATION", basePrice: 1000, taxPercent: 0 },
    { code: "CON-004", name: "Follow-up Consultation (within 7 days)", category: "CONSULTATION", basePrice: 300, taxPercent: 0 },
    { code: "CON-005", name: "Teleconsultation", category: "CONSULTATION", basePrice: 400, taxPercent: 0 },
    { code: "CON-006", name: "Diet counselling", category: "CONSULTATION", basePrice: 300, taxPercent: 0 },
    { code: "CON-007", name: "Lactation consulting", category: "CONSULTATION", basePrice: 500, taxPercent: 0 },
    { code: "CON-008", name: "Pediatric Psychology Consultation", category: "CONSULTATION", basePrice: 1000, taxPercent: 0 },
    { code: "CON-009", name: "Physiotherapy Assessment", category: "CONSULTATION", basePrice: 500, taxPercent: 0 },
    { code: "CON-010", name: "Dental Checkup", category: "CONSULTATION", basePrice: 400, taxPercent: 0 },

    // LAB
    { code: "LAB-001", name: "Complete Blood Count (CBC)", category: "LAB", basePrice: 350, taxPercent: 0 },
    { code: "LAB-002", name: "Blood Culture and Sensitivity", category: "LAB", basePrice: 1200, taxPercent: 0 },
    { code: "LAB-003", name: "Liver Function Test (LFT)", category: "LAB", basePrice: 800, taxPercent: 0 },
    { code: "LAB-004", name: "Renal Function Test (RFT)", category: "LAB", basePrice: 800, taxPercent: 0 },
    { code: "LAB-005", name: "Arterial Blood Gas (ABG)", category: "LAB", basePrice: 600, taxPercent: 0 },
    { code: "LAB-006", name: "Serum Bilirubin (Total, Direct, Indirect)", category: "LAB", basePrice: 400, taxPercent: 0 },
    { code: "LAB-007", name: "Thyroid Stimulating Hormone (TSH)", category: "LAB", basePrice: 500, taxPercent: 0 },
    { code: "LAB-008", name: "Thyroid Profile (T3, T4, TSH)", category: "LAB", basePrice: 1000, taxPercent: 0 },
    { code: "LAB-009", name: "C-Reactive Protein (CRP) Quantitative", category: "LAB", basePrice: 500, taxPercent: 0 },
    { code: "LAB-010", name: "Urine Routine and Microscopic", category: "LAB", basePrice: 200, taxPercent: 0 },
    { code: "LAB-011", name: "Urine Culture", category: "LAB", basePrice: 800, taxPercent: 0 },
    { code: "LAB-012", name: "Stool Routine", category: "LAB", basePrice: 200, taxPercent: 0 },
    { code: "LAB-013", name: "Dengue NS1 Antigen", category: "LAB", basePrice: 600, taxPercent: 0 },
    { code: "LAB-014", name: "Dengue IgG/IgM Antibodies", category: "LAB", basePrice: 800, taxPercent: 0 },
    { code: "LAB-015", name: "Malaria Parasite Smear", category: "LAB", basePrice: 150, taxPercent: 0 },
    { code: "LAB-016", name: "Widal Test", category: "LAB", basePrice: 300, taxPercent: 0 },
    { code: "LAB-017", name: "Serum Electrolytes (Na, K, Cl)", category: "LAB", basePrice: 450, taxPercent: 0 },
    { code: "LAB-018", name: "Serum Calcium", category: "LAB", basePrice: 250, taxPercent: 0 },
    { code: "LAB-019", name: "Vitamin D3", category: "LAB", basePrice: 1500, taxPercent: 0 },
    { code: "LAB-020", name: "Vitamin B12", category: "LAB", basePrice: 1200, taxPercent: 0 },
    { code: "LAB-021", name: "Random Blood Sugar (RBS)", category: "LAB", basePrice: 100, taxPercent: 0 },
    { code: "LAB-022", name: "HbA1c", category: "LAB", basePrice: 600, taxPercent: 0 },
    { code: "LAB-023", name: "Prothrombin Time (PT/INR)", category: "LAB", basePrice: 400, taxPercent: 0 },
    { code: "LAB-024", name: "Blood Group & Rh Type", category: "LAB", basePrice: 200, taxPercent: 0 },
    { code: "LAB-025", name: "COVID-19 RT-PCR", category: "LAB", basePrice: 800, taxPercent: 0 },

    // PROCEDURE
    { code: "PRO-001", name: "IV Cannulation", category: "PROCEDURE", basePrice: 200, taxPercent: 0 },
    { code: "PRO-002", name: "Lumbar Puncture", category: "PROCEDURE", basePrice: 1500, taxPercent: 0 },
    { code: "PRO-003", name: "Endotracheal Intubation", category: "PROCEDURE", basePrice: 2000, taxPercent: 0 },
    { code: "PRO-004", name: "Phototherapy (per day)", category: "PROCEDURE", basePrice: 1000, taxPercent: 0 },
    { code: "PRO-005", name: "Nebulization (per session)", category: "PROCEDURE", basePrice: 150, taxPercent: 0 },
    { code: "PRO-006", name: "Oxygen Therapy (per hour)", category: "PROCEDURE", basePrice: 100, taxPercent: 0 },
    { code: "PRO-007", name: "Chest Tube Insertion", category: "PROCEDURE", basePrice: 3000, taxPercent: 0 },
    { code: "PRO-008", name: "Central Venous Line Insertion", category: "PROCEDURE", basePrice: 2500, taxPercent: 0 },
    { code: "PRO-009", name: "Umbilical Catheterization (UVC/UAC)", category: "PROCEDURE", basePrice: 3500, taxPercent: 0 },
    { code: "PRO-010", name: "Surfactant Administration", category: "PROCEDURE", basePrice: 1500, taxPercent: 0 },
    { code: "PRO-011", name: "Exchange Transfusion", category: "PROCEDURE", basePrice: 5000, taxPercent: 0 },
    { code: "PRO-012", name: "Bone Marrow Aspiration", category: "PROCEDURE", basePrice: 2000, taxPercent: 0 },
    { code: "PRO-013", name: "Wound Dressing (Minor)", category: "PROCEDURE", basePrice: 200, taxPercent: 0 },
    { code: "PRO-014", name: "Wound Dressing (Major)", category: "PROCEDURE", basePrice: 500, taxPercent: 0 },
    { code: "PRO-015", name: "Suturing (Minor)", category: "PROCEDURE", basePrice: 800, taxPercent: 0 },
    { code: "PRO-016", name: "Plaster Application", category: "PROCEDURE", basePrice: 1000, taxPercent: 0 },
    { code: "PRO-017", name: "Vaccination Administration", category: "PROCEDURE", basePrice: 100, taxPercent: 0 },
    { code: "PRO-018", name: "Gastric Lavage", category: "PROCEDURE", basePrice: 600, taxPercent: 0 },
    { code: "PRO-019", name: "Catheterization (Urinary)", category: "PROCEDURE", basePrice: 400, taxPercent: 0 },
    { code: "PRO-020", name: "Enema Administration", category: "PROCEDURE", basePrice: 300, taxPercent: 0 },

    // ROOM
    { code: "ROM-001", name: "General Ward Bed (per day)", category: "ROOM", basePrice: 1000, taxPercent: 0 },
    { code: "ROM-002", name: "Semi-Private Room (per day)", category: "ROOM", basePrice: 2500, taxPercent: 0 },
    { code: "ROM-003", name: "Private Room (per day)", category: "ROOM", basePrice: 4000, taxPercent: 0 },
    { code: "ROM-004", name: "NICU Bed/Incubator (per day)", category: "ROOM", basePrice: 6000, taxPercent: 0 },
    { code: "ROM-005", name: "PICU Bed (per day)", category: "ROOM", basePrice: 7000, taxPercent: 0 },
    { code: "ROM-006", name: "Isolation Room (per day)", category: "ROOM", basePrice: 3500, taxPercent: 0 },
    { code: "ROM-007", name: "Day Care Bed (up to 6 hrs)", category: "ROOM", basePrice: 800, taxPercent: 0 },
    { code: "ROM-008", name: "Emergency Observation", category: "ROOM", basePrice: 500, taxPercent: 0 },

    // MISC
    { code: "MSC-001", name: "Ambulance Transfer (Local)", category: "MISC", basePrice: 1500, taxPercent: 0 },
    { code: "MSC-002", name: "Ambulance Transfer (Outstation per km)", category: "MISC", basePrice: 25, taxPercent: 0 },
    { code: "MSC-003", name: "Birth Certificate Processing", category: "MISC", basePrice: 200, taxPercent: 0 },
    { code: "MSC-004", name: "Medical Records Copy", category: "MISC", basePrice: 300, taxPercent: 0 },
    { code: "MSC-005", name: "Diet/Food Services (per day)", category: "MISC", basePrice: 400, taxPercent: 0 },
    { code: "MSC-006", name: "Registration Fee", category: "MISC", basePrice: 150, taxPercent: 0 },
    { code: "MSC-007", name: "Admission Charge", category: "MISC", basePrice: 500, taxPercent: 0 },
    { code: "MSC-008", name: "Medical Certificate", category: "MISC", basePrice: 200, taxPercent: 0 },
    { code: "MSC-009", name: "Equipment Monitor Charge (per day)", category: "MISC", basePrice: 800, taxPercent: 0 },
    { code: "MSC-010", name: "Biomedical Waste Handling", category: "MISC", basePrice: 100, taxPercent: 0 },
] as const;
